// <auto-generated />
namespace HandIn4.Migrations
{
    using System.CodeDom.Compiler;
    using System.Data.Entity.Migrations;
    using System.Data.Entity.Migrations.Infrastructure;
    using System.Resources;
    
    [GeneratedCode("EntityFramework.Migrations", "6.1.3-40302")]
    public sealed partial class readingvirtual : IMigrationMetadata
    {
        private readonly ResourceManager Resources = new ResourceManager(typeof(readingvirtual));
        
        string IMigrationMetadata.Id
        {
            get { return "201612021107298_readingvirtual"; }
        }
        
        string IMigrationMetadata.Source
        {
            get { return null; }
        }
        
        string IMigrationMetadata.Target
        {
            get { return Resources.GetString("Target"); }
        }
    }
}
